### ISSUE TITLE
FR: export SCORM as single-sco

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#102]
It would be an HTML export with SCORM related js functions.

**Comment by ignaciogros** [comment]
See this request: http://exelearning.net/forums/topic/exelearning-se-sigue-llevando-mal-con-calificacones-en-moodle/

**Comment by jm-andonegi** [comment]
[scorm_jmandonegi01.zip](https://github.com/exelearning/iteexe/files/1553308/scorm_jmandonegi01.zip)
Just al little example showing how can be an iframe containing all contents.

**Comment by ignaciogros** [comment]
We won't do this for the moment. We decided ([here](http://descargas.educalab.es/cedec/proyectoedia/jornadasedia/resumen_iijornadasedia/)) that there will be self-assessment and reinforcement activities, as they've been since the beginning of the project. 

We'll improve other parts of eXe before doing that.

In case those improvements can be done, the Single-SCO export will be the first one.

Thanks a lot for the examples and your explanations in that meeting, @jm-andonegi!
