### ISSUE TITLE
FR: improve grade management in SCORM export

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#103]
- Add grade management to all interactive activities
- Control all feedback fields to show/hide them depending of SCORM launch mode.
- Add feedback to SCORM test

**Comment by ignaciogros** [comment]
See this request: http://exelearning.net/forums/topic/exelearning-se-sigue-llevando-mal-con-calificacones-en-moodle/

**Comment by ignaciogros** [comment]
We won't do this for the moment. We decided ([here](http://descargas.educalab.es/cedec/proyectoedia/jornadasedia/resumen_iijornadasedia/)) that there will be self-assessment and reinforcement activities, as they've been since the beginning of the project. 

We'll improve other parts of eXe before doing that.
