### ISSUE TITLE
No grammer restraints reported by Eclipse

### ISSUE THREAD

**Issue by videophonegeek** [exelearning/iteexe#15]
All the XML files in the themes, and the generated contentv3.xml need the <!DOCTYPE (parent)> added like this:
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE instance>
<instance xmlns="http://www.exelearning.org/content/v0.3" reference="2" version="0.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemalocation="http://www.exelearning.org/content/v0.3 content.xsd" class="exe.engine.package.Package">
 <dictionary>
...
This silences the DTD no grammer restraints warning.

**Comment by ignaciogros** [comment]
Hi John,

Could you check the attached XML file (it's a Style's config.xml file). We could provide more information, but if that's enough (I think so) I'll do that in all the Styles.

Thank you.

[config.zip](https://github.com/exelearning/iteexe/files/185750/config.zip)

**Comment by ignaciogros** [comment]
"XML does not require a DTD/Schema.

When you are experimenting with XML, or when you are working with small XML files, creating DTDs may be a waste of time.

If you develop applications, wait until the specification is stable before you add a document definition. Otherwise, your software might stop working because of validation errors".

Source: http://www.w3schools.com/xml/xml_dtd.asp

Those files are only to be used inside eXe. I attach Base Style's config.xml file, with and without DOCTYPE. 

Please reopen it you think that that information is necessary.

[base_style_config_file.zip](https://github.com/exelearning/iteexe/files/207974/base_style_config_file.zip)
