### ISSUE TITLE
base.css on preview mode

### ISSUE THREAD

**Issue by antton** [exelearning/iteexe#156]
Morning, 

Why everytime I try to check my content via preview mode the only css files used from my theme are nav.css and content.css?

The base.css used by the preview mode is from the styles root folder.

I think it should take the base.css file from the active theme folder.

Cheers!

**Comment by ignaciogros** [comment]
Thanks @antton.

base.css will include the required CSS code. It changes from version to version. That's why we recommend to use eXe's instead of the Style's. 

But **it was as you say before**. 

@JuanCasanovaSdweb:

See getFilesCSSToMinify in common.py. It overwrites the Style's base.css file. It's not what's recommended, but if the Style has its own base.css file, it should be used instead of eXe's. No compression is needed in that case.

As you'll see, that's how it works inside eXe (add a base.css to any Style to see it).

**Comment by JuanCasanovaSdweb** [comment]
I kept the compression on this case, I think it makes more sense to compress the file even if it is not the one that comes with eXe.

@ignaciogros: Reopen this issue if you really think we shouldn't compress it.

**Comment by ignaciogros** [comment]
It's just because we don't know what's in that file, and the compression might fail, but if you think that that can't happen it's OK to compress it.

Thanks.

**Comment by antton** [comment]
Even minifying the base.css we can still check inside what it have. I think we should let it compress IMHO.

Thanks!
