### ISSUE TITLE
Version file in config folder

### ISSUE THREAD

**Issue by JuanCasanovaSdweb** [exelearning/iteexe#162]
From a [post on the forum](http://exelearning.net/forums/topic/exe-no-abre-en-xubuntu-16-04/), we have discovered that there is a "version" file that is created on the config directory every time eXe starts.

For an unknown reason, eXe didn't write anything in it and now can't start.

This file is used and created in [application.py](https://github.com/exelearning/iteexe/blob/master/exe/application.py#L113) and we probably can just remove it and use the real eXe version to do the same.

@pedropena, @jrfern, @ignaciogros, is there any other place where this file is needed? Or a reason for it to be done this way?

**Comment by pedropena** [comment]
In eXe we track the version of the objects too, not only the global
version. This is needed because some objects are persisted in disk. In the
case of the Application object, it is not persisted in disk, but we use the
same mechanism (objects has is own version) to do some maintenance tasks
like in
https://github.com/exelearning/iteexe/blob/master/exe/application.py#L125.

I think that a quick fix is to catch possible exceptions turning the
contents of the version file to integer and if something happens assume
version 0 to trigger again all the maintenance scripts that should be
written assuming that can be executed multiple times. And maybe add checks
after writing to the version file.

**Comment by JuanCasanovaSdweb** [comment]
Solved then, I've added a fallback when it's not possible to get the object version from the file.
