### ISSUE TITLE
Content weight when using too much videos

### ISSUE THREAD

**Issue by antton** [exelearning/iteexe#199]
Hi, this is not a bug just a recommendation!!

I would be nice to make an effort adding some options to make the video loading faster, sometimes we use a lot of external (youtube, vimeo...) videos in our content it result on a slow loading pages.

https://varvy.com/pagespeed/defer-videos.html

I let this blog article explaining a particular solution.

Cheers!

**Comment by ignaciogros** [comment]
Hi, @antton.

**Thanks for the tip.** 

All the steps described in the link can be followed in eXe:

1. Get the embed code of video you want
2. Alter the embed code as described above
3. Add the script to bottom of page (Properties tab - Footer in eXe)

I don't think that we should do that in all cases, because that will make the IFRAME content depend on JavaScript. Please tell me if you think I'm wrong.
