### ISSUE TITLE
Still not comfortable with the fMath fonts

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#203]
I still find several issues with the new fonts added to the repository when the fMath tool was included (see webui/tools/fMath/fonts/):

1. I see no license for the fonts; are they covered by the fMath license? Were they downloaded from the fMath site? I can't find a link to them there (maybe my fault)

2. Several "versions" of the fonts are included: .eot., .ttf, .woff. Which one is used? Do we have to include them all?

3. Three of the six of them exist as packaged fonts in Debian: fonts-oflb-asana-math, fonts-dejavu and fonts-stix. Using the packaged forms would cut down the size of the eXe package and would save us maintenance and updating work.

4. Is it necessary to include the six of them? Are any of them aesthetic alternatives or are they necessary for multilingual support or additional mathematical notation?

**Comment by ignaciogros** [comment]
This commit fixes that: cabf022d2a47a2a40b46dbbc4dc075bbafdc097f

This is what the author of the formula editor says: 

> The fonts are required :
> - to have the same "drawing" for all the clients
> - to have the same symbols for char codes
> 
> Yes, you can remove any fonts, but keep the main "STIX" libraries.
> (also you need to remove the lines from fmathFormulaFonts.js)

So in order to have the same "drawing" for all the clients we should keep as much fonts as possible. 

I checked the licenses and included the required references in eXe's Legal Notes. I had to remove this fonts due to license incompatibilities: Diwani Letter (I found that it was designed for Microsoft Corp. by Platinum Inc, but I couldn't find the license) and 'trado' (unknown license).

The folder is still quite heavy because of the 'dejavu' font. I think that we should keep it unless we're sure that there will be no presentation problems in any case.

Thanks for the reminder, Juan Rafael.

**Comment by ignaciogros** [comment]
Hi, @jrfern.

> I see no license for the fonts; are they covered by the fMath license? Were they downloaded from the fMath site? I can't find a link to them there (maybe my fault)

Legal Notes page in master. The required licenses are included in the folders where the fonts are.

> Several "versions" of the fonts are included: .eot., .ttf, .woff. Which one is used? Do we have to include them all?

Yes. We have to include them. Not every OS/browser will use the same version.

> Three of the six of them exist as packaged fonts in Debian: fonts-oflb-asana-math, fonts-dejavu and fonts-stix. Using the packaged forms would cut down the size of the eXe package and would save us maintenance and updating work.

The font included in eXe will only be used when the font is not installed. I think that we should keep them. Other option will be to include them just for other OS, but I think that we should keep that simple.

> Is it necessary to include the six of them? Are any of them aesthetic alternatives or are they necessary for multilingual support or additional mathematical notation?

The plugin programmer told us to keep them 'to have the same "drawing" for all the clients' and 'to have the same symbols for char codes'. 

Maybe we should remove any editor from eXe. I asked some LaTeX users, but I had no answer. The editor might be useful for some users anyway, so I think that we should include it until we have that clear.

**Comment by jrfern** [comment]
On 25 July 2017 at 10:24, Ignacio Gros <notifications@github.com> wrote:

> The font included in eXe will only be used when the font is not installed. I think that we should keep them. Other option will be to include them just for other OS, but I think that we should keep that simple.

I can't believe that, whatever the OS,  any application that uses
dejavu, for instance, should have to include its own copy of the font.
That's what dependences are for. Bloated packages that include their
own copies of java, the fonts, common libraries etc. are badly built
packages.

As an example, LibreOffice in Debian depends on default-jre |
sun-java6-jre | java6-runtime | jre,  fonts-liberation,
fonts-opensymbol and recommends fonts-dejavu and other fonts, it does
not include a copy of its own java or fonts in the package.

I don't know how this is solved in the other OS, but it's the way to
go in Debian GNU Linux.

**Comment by ignaciogros** [comment]
This is how CSS font-face works: https://developer.mozilla.org/es/docs/Web/CSS/@font-face

Some Styles, like Kids, have fonts too.

If we remove all those fonts from the package there will be presentation problems. We can't (not enough time for that right now) revise the plugin code. If there are problems with the licenses I think that we should remove it. Otherwise, we should try to keep it changing as less as possible, as we do with other third party code.
