### ISSUE TITLE
Installation language

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#212]
Can this be solved? My SO is in Spanish, but the installation windows are in English.

Please close if it's not possible or label as FR if needed.

Thanks.

**Comment by JuanCasanovaSdweb** [comment]
There are two part for this issue:

1. Translate the installer: pretty easy as we only have to add the language to its file (https://github.com/exelearning/iteexe/blob/master/installs/windows/exe.nsi#L37). The main problem here is that may be some languages in eXe that are not available on NSIS (Galician maybe?).

2. Translate the left side and the license agreement. I don't event know if this is completely possible, so we will have to look more into it. This would also mean more strings to translate (that's why i marked it as an FR).
