### ISSUE TITLE
ePub & Readium: JavaScript is not working

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#258]
I downloaded an ePub from [this page](http://azardi.infogridpacific.com/resources.html) ('Year Five Maths: Operations on Numbers') and the JavaScript works in Google Chrome + Readium, but when the ePub is created with eXe it doesn't work. I even tried with eXe 2.04 (those ePubs used to work).

We have to try to make them work again. Did something change in Readium?

**Comment by JuanCasanovaSdweb** [comment]
I think I found the issue. It's not exactly a Readium issue but a Chrome Apps one.
It seems like Chrome Apps can't execute inline JS inside their HTML due to their [security policy](https://developer.chrome.com/extensions/contentSecurityPolicy#JSExecution). This makes it impossible to eXe to execute this script at the start of each page:

```html
<script type="text/javascript">document.body.className+=" js"</script>
```

We could solve this easily just by putting that inline in a external file (common.js seems to be the best one?).

The actual problem is that this is used in other parts of eXe (some activities define an inline onclick for its buttons) so we would have to review everything and change it to use a external file.

**Comment by ignaciogros** [comment]
Thanks, @JuanCasanovaSdweb. That's it.

It refuses to execute inline JavaScript because it violates the Content Security Policy directive.

I tried to allow inline JavaScript execution, but I couldn't. This is what I tried: https://stackoverflow.com/questions/30280370/how-does-content-security-policy-work (see also https://developers.google.com/web/fundamentals/security/csp/?hl=es#la_metaetiqueta)

Please tell me if you find how to apply that.

**More:**

f229589e7da38798f905956eb3d64a270047efec makes JavaScript work in many cases (Free Text iDevices, iDevice togglers, FX, definition lists and iDevices with feedback), but we have to improve that:

1. As you'll see, $exe_i18n is defined in common.js instead of being in the HTML right before that file is included (see common.py - getJavaScriptStrings). Can we include that object in common.js using Python when exporting? If you can do that, I'll do the next point:

2. Revise other iDevices. Most of the interactive activities are not working. We should do the same as in the other cases: No inline JavaScript at all.

But finding the way to change that policy would be easier...

Thanks.

**Comment by ignaciogros** [comment]
You can now add most iDevices. The iDevice togglers and the hints (instructions) will work and there will be no JavaScript errors.

**Interactive iDevices that work:**

* Multi-choice
* True-False Question
* Multi-select

**iDevices that don't work but can be used (they are properly displayed):**

Notice that **they might work in other ePub readers**, but not in Readium due to the app Content Security Policy.

* DropDown Activity: The feedback works, but it won't check. An error message (Error recovering data. This might not work in this ePub reader.) is shown when clicking on 'Check'.
* SCORM Quiz: An error message is shown.
* Cloze Activity: An error message is shown.
* Image Gallery: An error message is shown.
* Scrambled List (new): An error message is shown (This activity does not work in ePub.).

**Comment by JuanCasanovaSdweb** [comment]
@ignaciogros:

Should it really be included in common.js? Wouldn't it be better to include it in a completely separate file?

This way we won't have to mess with common.js, which would be exported as it is.

I don't think is that much of a problem to include it, but I do think that it would be better to manage common.js in the future if Python doesn't have to modify it when exporting.

**Comment by ignaciogros** [comment]
Hi,

> Should it really be included in common.js? Wouldn't it be better to include it in a completely separate file?

common.js contains code that is used almost everywhere in eXe. It could contain the strings that that code uses too. There will be one less request, but it's cleaner as you say, and you can overwrite the exported version with the uncompressed one for debugging or adding new functionalities. So it's OK if those strings are in a different file (common_i18n.js?).

**Thanks!**

**Comment by JuanCasanovaSdweb** [comment]
We had already created one called lang.js but your name is better. 

In fact we were creating two files (one general and one for games) but we are changing it so it only uses one file.

So, today we will push a commit with this two changes which I guess means this issue is fixed and can be closed, right @ignaciogros?

**Comment by ignaciogros** [comment]
Thanks, @JuanCasanovaSdweb!
