### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#365]
- New Package.
- Try to publish in Procomún.
- Write the title and the description, the author's name and choose a resource type.
- Click on "Save and export" and confirm, but instead of clicking on "Yes, I authorize this request", click on "Cancelar". Then you'll get an ugly error message... Can eXe handle that?

**Comment by JuanCasanovaSdweb** [comment]
We could totally do this, and it should be pretty simple. It's only a matter of adding a new exception type to this part and call a warning in the client side (the same way is done if there is an error with the ClientId o ClientSecret):
https://github.com/exelearning/iteexe/blob/2e35490141211fc533b069ea6e5a3011b9e480cd/exe/webui/oauthpage.py#L56-L68

The problem here is actually that we need a new string, so I think we should leave it for the next version (it doesn't really make sense to just put the same error as with the other case as it would not be of any help to the user).

For now, I'm marking this as an FR.

**Comment by ignaciogros** [comment]
Maybe we could just close the modal window (that's what the user expects when clicking on "Cancel"). No new strings required.
