### ISSUE TITLE
Error uninstalling: Missing DLL

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#379]
I just downloaded and installed 2.3, but...

![win-error](https://user-images.githubusercontent.com/2928868/50000652-7f43db00-ff9a-11e8-9e78-51771fc3ee28.png)

Is that a bug? Thanks...

**Comment by JuanCasanovaSdweb** [comment]
Ok, this is a weird one.

First of all, the uninstaller is created on install, so if there was a problem was actually with the installer of the previous version you had installed (which would the actual error was in a previous version of eXe).

Moreover, the uninstaller should have everything it needs in eXe's folder. The problem here is actually that is looking for version l1-1-1 of the DLL when it should be looking for version l1-1-0.

If I had to guess, I would say it has something to do with an update to Visual C++ Redistributable (installed with eXe) and we should see if this happens again to someone (I just did a full update from 2.2 to 2.3 and never saw this error).

Closing this for now, if you think something's not right feel free to reopen it!
