### ISSUE TITLE
Should we allow fonts in style folders?

### ISSUE THREAD

**Issue by jrfern** [exelearning/iteexe#392]
**$ grep -R ".woff2" ***
exe/webui/style/INTEF/content.css:  src: local('Encode Sans Light'), local('EncodeSans-Light'), url(EncodeSans-Light_vietnamese.woff2) format('woff2');
exe/webui/style/INTEF/content.css:  src: local('Encode Sans Light'), local('EncodeSans-Light'), url(EncodeSans-Light_latin-ext.woff2) format('woff2');
exe/webui/style/INTEF/content.css:  src: local('Encode Sans Light'), local('EncodeSans-Light'), url(EncodeSans-Light_latin.woff2) format('woff2');
exe/webui/style/kids/content.css:  src: local('Open Sans'), local('OpenSans'), url(open-sans.woff2) format('woff2'), url(open-sans.woff) format('woff');
exe/webui/style/kids/content.css:  src: local('Open Sans Bold'), local('OpenSans-Bold'), url(open-sans-bold.woff2) format('woff2'), url(open-sans-bold.woff) format('woff');
exe/webui/style/simplepoint/content.css:  src: local('Open Sans'), local('OpenSans'), url(open-sans.woff2) format('woff2'), url(open-sans.woff) format('woff');
exe/webui/style/simplepoint/content.css:  src: local('Open Sans Bold'), local('OpenSans-Bold'), url(open-sans-bold.woff2) format('woff2'), url(open-sans-bold.woff) format('woff');

**It doesn't seem reasonable to have copies and copies of the same files in the different style folders.**

**Comment by ignaciogros** [comment]
**> Should we allow fonts in style folders?**

I think so. It's the way to use the font family that you want when it's not installed. Fonts are part of the presentation, just as the background images (iDevice icons, etc.) defined in the CSS files. eXe could also have a fonts folder, but that would be too complex for such a simple thing. There won't be many fonts anyway, because we'll remove most of the current Styles.

Please close if you agree.

Thanks!

**Comment by jrfern** [comment]
Not convinced, but I accept your view.
