### ISSUE TITLE
elp keeps images after deleting them

### ISSUE THREAD

**Issue by cristinavaldera** [exelearning/iteexe#396]
When you open an existing elp and delete an existing image, the image keeps on appearing in the folder when exporting as html.

This is important, and it happens with other files too. See #423

**Comment by ignaciogros** [comment]
This happens in 2.3.1 and master.

* Open an elp with images.
* Delete an image an save.
* Use the Resources Report option (the image will be there).
* Export and check that the image is not in any page.

It's important, because the package can get really heavy because of that. It probably happens with other formats too.

**Comment by ignaciogros** [comment]
We'll apply this solution until the new file manager works:
When trying to add a file that exists (same name with or without the same content), eXe should ask if you want to replace it or upload it with a different name (rename it, just as eXe does right now).
It's not the perfect solution, but at least we'll get smaller packages.

**Comment by ignaciogros** [comment]
Included in eXe 2.5.
