### ISSUE TITLE
New version message: Use the GitHub API instead of the current JS file

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#400]
Use the GitHub API instead of exelearning-info.js. Thanks for suggesting this, @david-puente

**Comment by jrfern** [comment]
This is only a question. One of our original principles was that you don't need an internet connection to use eXeLearning. Now this solution introduces a call to https://api.github.com/ (a non-totally free site owned by Microsoft, by the way) everytime you start eXe, doesn't it? What happens if the user doesn't have a connection or blocks calls to third party sites? Is an error message produced? 

Please feel free to close again if you find this unimportant.

**Comment by ignaciogros** [comment]
eXe checks if it's online before trying to load that URL, and if the request is blocked, nothing happens. All the code is in that server now, and that URL is automatically updated when there's a new release. I think it's the best way to check that. We used a file in eXe's domain before, but we changed that so we don't have to update that file manually.
