### ISSUE TITLE
Can't preview page

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#418]
**Windows 10 + Chrome:**

Preview does not work:

`<type 'exceptions.AttributeError'>: Application instance has no attribute 'previewPage'`

Error reported by @guerreroherrero

**It works for me.** Can you test that, @david-puente please?

**Comment by JuanPerezSdweb** [comment]
Hello,

We were unable to reproduce the error. If @guerreroherrero can provide us an elp in which reproduce the error, we can try to reproduce it again.

**Comment by guerreroherrero** [comment]
Hello,

I've seen that it happens only with certain elp files. I don't know if it is just by chance, but I observed that the files in English language are those which fail to be previewed. Or maybe it is because of the eXe version in which they were produced, because the ones I tried in Spanish were produces in earlier versions of eXe.

This is an example of elp file I couldn't preview. It's a zipped elp file, so please, uncompress before using:

[Module6CourseDevelopment.zip](https://github.com/exelearning/iteexe/files/3309613/Module6CourseDevelopment.zip)

Thanks!!!

**Comment by ignaciogros** [comment]
It's true. Thanks, @guerreroherrero.

It's because it can't find a folder. Provisional solution (at least you'll be able to export): Go to the path where eXe's installed and create an empty folder called "export" here (there's already one called "edition"): scripts/idevices/pbl-tools/

**We should fix this as soon as possible.** Could you check that, @david-puente, please?

**Comment by ignaciogros** [comment]
Hi @guerreroherrero:

Was that elp created with the first 2.4 test version? In that case, that might be the problem.

If that is the case. You can recover the content adding a new Task iDevice to replace each of your elp's. Just copy and paste the content. The bad news is that you'll have to add the images again, or they'd be lost (they'll be deleted when deleting the original iDevice).

Please tell us if that's the problem. If it is, I think that we can close this. If you added those iDevices with the official version (2.4), we should fix it as soon as possible.

Thank you.

**Comment by ignaciogros** [comment]
@david-puente:

It seems to fail when editing an elp created with 2.3.x with an ABP Tasks iDevice in it. That iDevice is now called Tasks, and it doesn't have the "export" folder, but it should work just as before.

Thanks.

**Comment by guerreroherrero** [comment]
Yes, @ignaciogros,  I had created that content with 2.3.x and lately I had been using the ABP Tasks iDevice quite often, because it let me choose the icons. Now I wonder what will happen with all those ABP Tasks when I  upgrade to 2.4.1. Will the conversion be smooth or will I lose my images in those iDevices?

I don't know if upgrading is safe in my case. Thanks!

**Comment by ignaciogros** [comment]
> Now I wonder what will happen with all those ABP Tasks when I upgrade to 2.4.1.

2.4.1's been released just to fix this bug. Those iDevices should work. You can save a copy of the elp you created with 2.3.x and try with that copy, just in case...

Thanks for reporting this issue. It was a big problem.

**Comment by jrfern** [comment]
I'm not going to reopen the issue, but I'm afraid we have a usability problem here - if we have improved iDevices ABP Task to new Task, and Free Text to Text, as a user I would expect a conversion when opening my .elp with 2.4.1, transforming ABP Task to Task and Free Text to Text, with a default icon. No-one needs two parallel sets of iDevices doing practically the same. Should I open a Feature Request?

What do you think, @ignaciogros, @guerreroherrero?

**Comment by guerreroherrero** [comment]
Hi! I agree with @jrfern 100%.

**Comment by ignaciogros** [comment]
> I agree with @jrfern

Me too.

The old ABP Tasks iDevice is now called Task, but that's the only difference between them. If you added one before, it'll be there as Task.

Free Text and Text are different iDevices. We want to make a conversion when opening the elp (you open an old one, and it becomes a Text one), but we didn't have time to do it. Thanks for reminding. We won't forget that.
