### ISSUE TITLE
Resources management: problems with .tex files 

### ISSUE THREAD

**Issue by jm-andonegi** [exelearning/iteexe#423]
[This forum thread](http://exelearning.net/forums/topic/imposible-subir-recurso-didactico-a-procomun/) reports serious problems with .tex files.
Resources managements mechanism should be documented.

**Comment by jm-andonegi** [comment]
The .elp keeps old files that are not being used. For instance, in page 1.5 Millora del projecte Trabuquet.zip file has been renamed and appears twice in resources (Trinquet.zip is no longer user but it is not removed from the .elp)

**Comment by ignaciogros** [comment]
> The .elp keeps old files that are not being used. 

It happens with other files too. See #396. I close this issue because it seems to be the same problem. It will be fixed when allowing structured contents. There will be many changes in the file management system, and they're really needed, so we preferred to work there instead of trying to improve the current one (we see that this has been failing for a long time now).

Thank you!
