### ISSUE TITLE
The idivice 'Interactive video' doesn't appear

### ISSUE THREAD

**Issue by criarrfer** [exelearning/iteexe#434]
I installed the new version yesterday and this improvment plus the others in this version are not 
available

**Comment by ignaciogros** [comment]
That's because the previous version preferences are preserved. Just check the "Advanced user" option and go to "Edit iDevices" (left panel).

You can also delete all your previous preferences (that will delete your custom iDevices and Styles too) removing this folder:

Linux: ~/.exe (Ctrl + H to see the hidden folders)
Windows XP: C:\Documents and Settings\YourUserName\Application Data\exe
Windows 7 y superiores: C:\Users\YourUserName\AppData\Roaming\exe
MAC: /Users/YourUserName/.exe

**Comment by criarrfer** [comment]
Thank you!
