### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [exelearning/iteexe#460]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing eXeLearning on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by ignaciogros** [comment]
Hi Leandro,
Thanks for your suggestion. We're currently working on a SNAP package. I hope we'll publish it soon. We decided that because of the large number of Ubuntu+eXeLearning users. I close the issue because we're evaluating other solutions too, including Flatpak, but we still don't know what will go after the SNAP package. Thank you!

**Comment by frandavid100** [comment]
Hi. Is there any news regarding a possible flatpak version?

**Comment by ignaciogros** [comment]
Hi @frandavid100,

This project's no longer maintained. 

Please see https://github.com/exelearning/exelearning/
