### ISSUE TITLE
It is possible to improve eXe to allow collaborative working treating contents with git versioning tool?

### ISSUE THREAD

**Issue by pedcremo** [exelearning/iteexe#483]
It is possible to improve eXe to allow collaborative working treating contents with git versioning tool?

I want to know if this issue is in your roadmap. It'll be awesome if a team could work collaboratively in the same eXe project. 

It could be feasible to improve eXe to allow publish/subscribe to a git repository to pull contents, work with them and then push back. And when we push back, for example to github, It would be possible too to publish as html content directly using github pages mechanism. The idea is to allow several people work together in the same git repository. Moreover, using git in our eXe projects we were empowered to detect conflicts with other people work and fix them, mantaining a proper contents project versioning with the ability to roll back if needed ...

I've been playing a little bit and the main drawback could be the eXe .elp format itself.

Marshaling the whole project in two single files: content.data and contentv3.xml definitively could not be the best to work with git that really shines when you deal with multiple files and people tweeking same project.

From general lack of awareness of eXe internals.It could be possible to use <!ENTITY XML feature as a mechanism to divide (and conquer) contentv3.xml in several files to acommodate to this requirement.  With ENTITY we have a tool to include external references, similarly as we do with software projects in order to atomize a complex/huge project in more manageable chunks.

If this suggested feature is something you really consider interesting I can put my two cents helping with the development.

Best Regards
Pere Crespo

**Comment by ignaciogros** [comment]
Hi Pere,

Thanks a lot for your suggestion. It's a great idea, but right now we have to update the code or even rewriting the application to avoid compatibility problems with Python 2 and some important libraries in eXe. Ubuntu 20.04 LTS release has Python 2 removed from the main repository. Solving that is our main goal now. Releasing a 100% online version is another one.

After that (it's a big work), we'll return to the roadmap. We talked about collaborative working before, but we didn't even start that because there were more urgent issues. It was seen as something interesting to do in the future. If eXeLearning is recoded, it might be a good time to think about doing it. Could you send an email to the address you'll find in https://exelearning.net/ (in the page footer) just to contact you in case that can be done? You seem to have a way to do it...

Thank you!

**Comment by ignaciogros** [comment]
We hope that this will be in future versions (after renewing the code), but it won't be in eXe 2+. Thank you very much for your ideas and, help, Pere!
