### ISSUE TITLE
Missing images!

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#485]
We're seeing many elp files with missing images. Example:

`<img src="WARNING_FILE=c:\users\ste\appdata\local\temp\tmpxmc3b5.eXe\previews\C__Users_STE_Desktop_exe_2.3.png=DOES_NOT_EXIST" alt="" width="100" height="100" />`

I don't know how to reproduce it, but it's important. I guess it's related to the last changes in the way the elp files are checked.

**Comment by ignaciogros** [comment]
Important: See #487 before trying to solve this. That might be a way to reproduce the problem.

**Comment by ManuelMayoSdweb** [comment]
Could it be the case that some users change the name of the image here?

![missing_images_test_01](https://user-images.githubusercontent.com/59160656/80490719-17f5b380-8962-11ea-9354-ce4c5c3a888e.PNG)

It is an easy way to replicate the error

**Comment by ManuelMayoSdweb** [comment]
The error: **WARNING_FILE=`<file-path>`=DOES_NOT_EXIST** occurs after checking that the image exists in the 'previewDir'

exe/engine/field.py
line 1907
```
if os.path.exists(file_name_str) and os.path.isfile(file_name_str):
    ...
else:
    ....
    filename_warning = "src=\"WARNING_FILE="+file_name_str +"=DOES_NOT_EXIST"
    new_content = new_content.replace(file_url_str, filename_warning)
```

**Comment by ignaciogros** [comment]
Hi,
That's where the error's thrown, but there should be no error.
The users are not changing the SRC field value. It's just that the image is not saved. 
Could it be that some paths (those containing some characters or something like that) fail? See [this comment](https://github.com/exelearning/iteexe/issues/487#issuecomment-621070459) in #487.

**Comment by ManuelMayoSdweb** [comment]
The error **WARNING_FILE=`<file-path>`=DOES_NOT_EXIST** 
it does seem that it is due to an inconsistency problem between the name of the file that is uploaded to **previews** and the name of the file that eXe stores internally.

This specific case does not have to do with changes to avoid unused images, but we are also not sure that this is the only case where images are not saved correctly. We would need more examples

**Comment by ignaciogros** [comment]
Hi @ManuelMayoSdweb. I just sent you an email with an example. I hope it helps.

**Comment by ManuelMayoSdweb** [comment]
The problem (or at least one of them) seems to be that in some new versions of some browsers (Google Chrome, Opera, etc) the iDevice save form is sent twice when you save the package while you are editing it.

**Comment by ignaciogros** [comment]
When is that method called ($exeAuthoring.iDevice.save())? Thank you.

**Comment by ManuelMayoSdweb** [comment]
When saving a package, the application checks if there is any open iDevice (in edition), in which case the save method of that iDevice is called.

**Comment by ManuelMayoSdweb** [comment]
I reopen the issue because it still fails on some occasions.

I think the main problem is that in some browsers iDevice save form submission is run twice instead of once.

An easy way to fix this would be to not delete the files from the user's temporary 'preview' folder after saving. But of course, this in itself would also be a problem.

**Comment by ignaciogros** [comment]
It was testing too. It still fails. I think that the previous commit does not change the behavior. Maybe you can revert that change.

Maybe we could save only when it's not saving. Something like:

```
var isSaving = false;
function exampleSave(){
	if (isSaving==false) {
		isSaving = true;
		// Save, and after saving:
		isSaving = false;
	}
}
exampleSave();
```
Will something like that work?

**Comment by ManuelMayoSdweb** [comment]
I think the problem was in trigger ("click") the button directly.
I hope it works better now!
