### ISSUE TITLE
Upload image instead of pasting a Base64 file

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#487]
In master, insert an image using the new "Image optimizer" option. You'll see that it works: It inserts a Base64 file that previewTinyMCEimageDragDrop uploads and transforms into a PNG image.

The problem is that you always get a PNG file, even if the image is a JPG or a GIF. 

**Two possible solutions:** 

1. Could eXe save the image with the right extension (see images_upload_handler in tinymce_4_settings.js)? But I couldn't get the extension there...

2. We could also upload the image before updating the SRC input value, like when you record an audio. I tried to do that, but the images are not saved. **Try this:**

- Go to webui/tools/image-compressor/js/main.js and change the value of eXeImageCompressor.type (it's "base64", use "file").
- Then try to insert images using the Image compressor. You'll see that the images are properly inserted in TinyMCE, but **they disappear** when you save the iDevice! This might be related to #485

**Comment by ignaciogros** [comment]
It works! Was it just this? `vm.$refs.input.value = '';` 
You also removed the timestamp. I added if to avoid image caching. Did that make if fail? Thank you!

**Comment by ignaciogros** [comment]
Sometimes you have to click on the "Finish" button more than once? Could you check that? Thank you.

**Comment by ManuelMayoSdweb** [comment]
The problem was the timestamp. For how eXe works when transferring images from **previews** to **resources**, the application needs the exact name of the image, but if we see how it works in this case we can see that the resource has a filename with the timestamp added, but it is uploaded to **previews** without the timestamp.

![exe_issue_487_1](https://user-images.githubusercontent.com/59160656/80578266-79705d80-8a08-11ea-94cd-0330d6eccc14.PNG)

![exe_issue_487_2](https://user-images.githubusercontent.com/59160656/80578529-dec44e80-8a08-11ea-916b-428e9c0b6ae8.PNG)

That doesn't matter to the web browser, because it ignores everything after "**?**", But eXe doesn't.

![exe_issue_487_3](https://user-images.githubusercontent.com/59160656/80578667-1df29f80-8a09-11ea-93e1-2a0698c82bc9.PNG)

![exe_issue_487_4](https://user-images.githubusercontent.com/59160656/80578685-2519ad80-8a09-11ea-8be1-25602fa37f68.PNG)

**Comment by ignaciogros** [comment]
Hi, @ManuelMayoSdweb.
The only problem I see now is that sometimes you have to click on the "Finish" button more than once.
Could you check that, please? I think that we can close this issue after fixing that.
