### ISSUE TITLE
Can't export (ePub)

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#503]
I can't export the attached elp (I tried ePub and web site exports). I get a "No such file or directory" message. I'm using Windows 7 / FF + 2.5 and master.

[aulavirtual.zip](https://github.com/exelearning/iteexe/files/4676019/aulavirtual.zip)

**Comment by ignaciogros** [comment]
Duplicated. See #510

**Comment by psetta** [comment]
It is not a problem of the export to "ePub" or "web site"  in particular.
In Windows there are problems when exporting packages that have nodes with a very long title because the default limit of a path cannot be greater than 260 characters (https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file).

I have made some small changes to allow longer paths to be used in Windows. But it would be advisable not to create nodes with very long titles in packages that are going to be exported on a Windows system.

**Comment by ManuelMayoSdweb** [comment]
It is not a problem of the export to "ePub" or "web site" in particular.
In Windows there are problems when exporting packages that have nodes with a very long title because the default limit of a path cannot be greater than 260 characters (https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file).

I have made some small changes to allow longer paths to be used in Windows. But it would be advisable not to create nodes with very long titles in packages that are going to be exported on a Windows system.

**Comment by ignaciogros** [comment]
It's not an important issue, but it fails. Open the attached elp, click on preview and then go to the second page. You'll get a 404 error. Is it easy to fix?

[long_name.zip](https://github.com/exelearning/iteexe/files/5429287/long_name.zip)

**Comment by ignaciogros** [comment]
Tested in eXe 2.6.1.

**Comment by ignaciogros** [comment]
Strange case. The node name was too long. Won't fix for the moment.
