### ISSUE TITLE
Min map editor. Sometimes it doesn't save the image.

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#507]
Add a Text iDevice, click on the "Mind map" button and try to add a map. You don't need to draw it, just open the editor and click on "Save" + "Crop and save". It doesn't always work. Most of the times, it fails the first time. 

I think that there's something wrong with the callback function in authoring.js (search "uploadMindMap"). Add an alert to show the value of the "target" var. Why is that method called more than once? It might be related with #487, but there's no timestamp in this case.

Thank you.

**Comment by ManuelMayoSdweb** [comment]
From what I see, the problem seems to be because the function of **authoring.js**: `uploadFileToResourcesCallback` (line 16560) doesn't always run.

The function should be executed when called from **mainpage.py**: `client.sendScript ('eXe.app.fireEvent ("uploadFileToResourcesDone")')` (line 950)

In fact it seems that if when it fails and keeps loading you manually run the function in the browser it works:

![Captura01](https://user-images.githubusercontent.com/59160656/84040543-09f47300-a9a3-11ea-8a0d-1f95198bed40.PNG)

![Captura02](https://user-images.githubusercontent.com/59160656/84040579-12e54480-a9a3-11ea-8c1a-6e59c43c3c96.PNG)
