### ISSUE TITLE
Problem to set default Style

### ISSUE THREAD

**Issue by arpablos** [exelearning/iteexe#526]
Hi

I'm having an issue when I try to change the default style. 

After I asked to @ignaciogros, I changed "defaultStyle" in the next locations:
- /exe/engine/config.py
- /exe/config/exe.conf

I stopped eXe and relaunch it with no changes.

Could you tell me if something is wrong?

Thanks in advance.

**Comment by ManuelMayoSdweb** [comment]
In the online version of eXe, each user has their own configuration file `/exe/config/<user>/exe.conf`.
Both the user configuration files and the general configuration file `/exe/config/exe.conf` are generated from `/exe/engine/config.py`. But once they are created changing the parameters in config.py will not change the configuration of the users themselves.

Therefore, if the users are already created, the file to be modified is `/exe/config/<user>/exe.conf`.

But there is an additional problem: by default, the base of the packages is linked to the INTEF style due to the template that is used. With the change I'm going to upload below, the behavior should be more appropriate.
