### ISSUE TITLE
Documentation for running in a webserver

### ISSUE THREAD

**Issue by mubinahmed** [exelearning/iteexe#622]
Hi Team,

Where can I find instructions to setup the application as a web application. 
I would like to avoid the installation of this application into every author's system.

**Comment by ignaciogros** [comment]
Sorry, but there's no official online version yet. We're working on a new eXeLearning version (100% new, written in PHP) which will be multi-user from the first moment, but there's still no release date.

You'll have to change a lot of things in eXe 2.6 to make it work online with different users, because it's not prepared for that, and we can't provide detailed instructions.
