### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by Sandra1Nikolic** [exelearning/iteexe#623]
Hello, 
I have been working with eXe in Serbian and I have noticed a mistake in the Serbian interface translation, test questions section. 

True-False question type has been translated as "Tačno-Pogrešno pitanje"  in the part where you select the type of question you want to add to the page. 

But, there is a typing error next to the radio button for the value "False". 

It is written "Pogređno" instead of "Pogrešno". 
![True False error](https://user-images.githubusercontent.com/103377363/164811205-5d63b333-7324-49b6-afae-34f3aa9b9fa7.JPG)

Thank you in advance for your understanding and time. 

Sincerely, 
Sandra

**Comment by jrfern** [comment]
I have fixed the misspelling, but you should take into account that the Serbian translation of eXeLearning hasn't been updated since 2008 (sic), and that 2389 messages and strings haven't been translated. The Serbian translation would use some help from native volunteers.
Thanks for taking part in the project.
