### ISSUE TITLE
Error when the node is called "Con"

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#98]
Create a new package and a node called "Con" and preview the result.

You'll get this error, at least in Windows 7 (master): twisted.python.filepath.InsecurePath

**Comment by JuanCasanovaSdweb** [comment]
The problem here is with Windows itself. You can't create a folder or a file with this name (if it's a file the extension doesn't seem to matter): 

> CON, PRN, AUX, CLOCK$, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9

Knowing this, I think we only have two options:

1. Don't allow to have these as node names. Faster, but would probably require a new string.
2. Renaming this nodes when exporting (or previewing). This is the better option, but I don't think we can do it before the release date (We can try but I can't make any promises ;)).

Anyone has a better idea?

**Comment by jrfern** [comment]
On 5 December 2016 at 18:54, JuanCasanovaSdweb <notifications@github.com> wrote:

> Renaming this nodes when exporting (or previewing). This is the better option, but I don't think we can do it before the release date (We can try but I can't make any promises ;)).
>
> Anyone has a better idea?

Rule number one: never publish with known bugs. So let's fix it, and
the other open bugs, then publish.

-- 
Juan Rafael Fernández
http://people.ofset.org/jrfernandez/

**Comment by ignaciogros** [comment]
I agree with @jrfern. We should fix that. I'd try to do it properly, renaming when exporting. Adding an underscore or a dash would be enough.

**Comment by JuanCasanovaSdweb** [comment]
It should be working now. If the node name is one of the forbidden list, it simply adds an underscore at the end of the it (only for links and filename).
We have tested it in Windows 10 and Ubuntu 14.04 (just to see if it was working fine).
